/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1.5rem",
        lg: "2rem",
        xl: "2.5rem",
        "2xl": "3rem",
      },
    },
    fontFamily: {
      poppins: ["Poppins", "Helvetica", "Arial", "sans-serif"],
      tajawal: ["Tajawal", "Helvetica", "Arial", "sans-serif"],
    },
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      padding: {
        section: "var(--padding-section)",
      },
      colors: {
        primary: {
          50: "var(--mantine-color-primary-0)",
          100: "var(--mantine-color-primary-1)",
          200: "var(--mantine-color-primary-2)",
          300: "var(--mantine-color-primary-3)",
          400: "var(--mantine-color-primary-4)",
          500: "var(--mantine-color-primary-5)",
          600: "var(--mantine-color-primary-6)",
          700: "var(--mantine-color-primary-7)",
          800: "var(--mantine-color-primary-8)",
          900: "var(--mantine-color-primary-9)",
        },
        secondary: {
          50: "var(--mantine-color-secondary-0)",
          100: "var(--mantine-color-secondary-1)",
          200: "var(--mantine-color-secondary-2)",
          300: "var(--mantine-color-secondary-3)",
          400: "var(--mantine-color-secondary-4)",
          500: "var(--mantine-color-secondary-5)",
          600: "var(--mantine-color-secondary-6)",
          700: "var(--mantine-color-secondary-7)",
          800: "var(--mantine-color-secondary-8)",
          900: "var(--mantine-color-secondary-9)",
        },
        accent: {
          50: "var(--mantine-color-accent-0)",
          100: "var(--mantine-color-accent-1)",
          200: "var(--mantine-color-accent-2)",
          300: "var(--mantine-color-accent-3)",
          400: "var(--mantine-color-accent-4)",
          500: "var(--mantine-color-accent-5)",
          600: "var(--mantine-color-accent-6)",
          700: "var(--mantine-color-accent-7)",
          800: "var(--mantine-color-accent-8)",
          900: "var(--mantine-color-accent-9)",
        },
        "accent-bg": {
          50: "var(--mantine-color-accent-bg-0)",
          100: "var(--mantine-color-accent-bg-1)",
          200: "var(--mantine-color-accent-bg-2)",
          300: "var(--mantine-color-accent-bg-3)",
          400: "var(--mantine-color-accent-bg-4)",
          500: "var(--mantine-color-accent-bg-5)",
          600: "var(--mantine-color-accent-bg-6)",
          700: "var(--mantine-color-accent-bg-7)",
          800: "var(--mantine-color-accent-bg-8)",
          900: "var(--mantine-color-accent-bg-9)",
        },
        success: {
          50: "var(--mantine-color-success-0)",
          100: "var(--mantine-color-success-1)",
          200: "var(--mantine-color-success-2)",
          300: "var(--mantine-color-success-3)",
          400: "var(--mantine-color-success-4)",
          500: "var(--mantine-color-success-5)",
          600: "var(--mantine-color-success-6)",
          700: "var(--mantine-color-success-7)",
          800: "var(--mantine-color-success-8)",
          900: "var(--mantine-color-success-9)",
        },
        danger: {
          50: "var(--mantine-color-danger-0)",
          100: "var(--mantine-color-danger-1)",
          200: "var(--mantine-color-danger-2)",
          300: "var(--mantine-color-danger-3)",
          400: "var(--mantine-color-danger-4)",
          500: "var(--mantine-color-danger-5)",
          600: "var(--mantine-color-danger-6)",
          700: "var(--mantine-color-danger-7)",
          800: "var(--mantine-color-danger-8)",
          900: "var(--mantine-color-danger-9)",
        },
        light: "var(--mantine-color-light-5)",
      },
    },
  },
  plugins: [],
};
